# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('Ticket_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
